version: '3'

services:
  ipfs:
    build:
      context: .
    container_name: ipfs
    restart: always
    # volumes:
    #   - ./config:/root/.ipfs
    logging:
      driver: json-file
      options: 
        max-size: "200k"
        max-file: "10"
    ports:
      # p2p (tcp and wss)
      - 4001:4001
      # http api
      - 127.0.0.1:5001:5001
      # gateway
      # - 8080:8080
